/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IDsOptimizationId } from '../../models/i-ds-optimization-id';

export interface OptimizationDeleteOptimization$Params {

/**
 * Parameter within the path for the id of an optimization.
 */
  optimizationId: IDsOptimizationId;
}

export function optimizationDeleteOptimization(http: HttpClient, rootUrl: string, params: OptimizationDeleteOptimization$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, optimizationDeleteOptimization.PATH, 'delete');
  if (params) {
    rb.path('optimizationId', params.optimizationId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

optimizationDeleteOptimization.PATH = '/v1/optimizations/{optimizationId}';
