/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncomingOptimizationOptimizationDefinition } from '../../models/incoming-optimization-optimization-definition';
import { OutgoingOptimizationOptimizationDefinition } from '../../models/outgoing-optimization-optimization-definition';

export interface OptimizationCreateOptimization$Params {
  
    /**
     * Data for the optimization.
     */
    body: IncomingOptimizationOptimizationDefinition
}

export function optimizationCreateOptimization(http: HttpClient, rootUrl: string, params: OptimizationCreateOptimization$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingOptimizationOptimizationDefinition>> {
  const rb = new RequestBuilder(rootUrl, optimizationCreateOptimization.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OutgoingOptimizationOptimizationDefinition>;
    })
  );
}

optimizationCreateOptimization.PATH = '/v1/optimizations';
