/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IDsResourceId } from '../../models/i-ds-resource-id';
import { IncomingResource } from '../../models/incoming-resource';

export interface ResourceUpdateResource$Params {

/**
 * Parameter within the path for the id of an resource.
 */
  resourceId: IDsResourceId;
  
    /**
     * Resource to be updated.
     */
    body: IncomingResource
}

export function resourceUpdateResource(http: HttpClient, rootUrl: string, params: ResourceUpdateResource$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, resourceUpdateResource.PATH, 'put');
  if (params) {
    rb.path('resourceId', params.resourceId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

resourceUpdateResource.PATH = '/v1/resources/{resourceId}';
