/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IDsResourceId } from '../../models/i-ds-resource-id';
import { OutgoingResource } from '../../models/outgoing-resource';

export interface ResourceGetResource$Params {

/**
 * Parameter within the path for the id of an resource.
 */
  resourceId: IDsResourceId;
}

export function resourceGetResource(http: HttpClient, rootUrl: string, params: ResourceGetResource$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingResource>> {
  const rb = new RequestBuilder(rootUrl, resourceGetResource.PATH, 'get');
  if (params) {
    rb.path('resourceId', params.resourceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OutgoingResource>;
    })
  );
}

resourceGetResource.PATH = '/v1/resources/{resourceId}';
