/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OutgoingResource } from '../../models/outgoing-resource';

export interface ResourceGetResources$Params {

/**
 * The number of the page to query.
 */
  page?: number;

/**
 * The number of elements per page.
 */
  pagesize?: number;
}

export function resourceGetResources(http: HttpClient, rootUrl: string, params?: ResourceGetResources$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OutgoingResource>>> {
  const rb = new RequestBuilder(rootUrl, resourceGetResources.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pagesize', params.pagesize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OutgoingResource>>;
    })
  );
}

resourceGetResources.PATH = '/v1/resources';
