/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IDsResourceId } from '../../models/i-ds-resource-id';

export interface ResourceDeleteResource$Params {

/**
 * Parameter within the path for the id of an resource.
 */
  resourceId: IDsResourceId;
}

export function resourceDeleteResource(http: HttpClient, rootUrl: string, params: ResourceDeleteResource$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, resourceDeleteResource.PATH, 'delete');
  if (params) {
    rb.path('resourceId', params.resourceId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

resourceDeleteResource.PATH = '/v1/resources/{resourceId}';
