/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Coordinates } from './models/coordinates';
export type { Error } from './models/error';
export type { ErrorDetails } from './models/error-details';
export type { ExpertiseId } from './models/expertise-id';
export type { RegionId } from './models/region-id';
export type { Resource } from './models/resource';
export type { ResourceConditions } from './models/resource-conditions';
export type { ResourceId } from './models/resource-id';
export type { SkillId } from './models/skill-id';
export type { SkillProficiency } from './models/skill-proficiency';
export type { SkillProficiencyLevelEnum } from './models/skill-proficiency-level-enum';
export type { TeamId } from './models/team-id';
export type { ValidationErrorDetails } from './models/validation-error-details';
