/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IncomingResource } from '../../models/incoming-resource';
import { OutgoingResource } from '../../models/outgoing-resource';

export interface ResourceCreateResource$Params {
  
    /**
     * Resource to be created.
     */
    body: IncomingResource
}

export function resourceCreateResource(http: HttpClient, rootUrl: string, params: ResourceCreateResource$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingResource>> {
  const rb = new RequestBuilder(rootUrl, resourceCreateResource.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OutgoingResource>;
    })
  );
}

resourceCreateResource.PATH = '/v1/resources';
