/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Date } from '../models/date';
export interface BidirectionalEscalatedCallsFilter {
  earliestRouteDate?: Date | null;
  latestRouteDate?: Date | null;
}
