/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Date } from '../models/date';
export interface BidirectionalRecordedCallsFilter {
  earliestEndDate?: Date | null;
  earliestStartDate?: Date | null;
  latestEndDate?: Date | null;
  latestStartDate?: Date | null;
}
