/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IDsResourceId } from '../models/i-ds-resource-id';

/**
 * Restrictions regarding where the call may be planned.
 */
export interface BidirectionalResourceRestrictions {

  /**
   * Resources the call can be exclusively assigned to.
   */
  allowedResources?: Array<IDsResourceId> | null;

  /**
   * Resources the call cannot be assigned to.
   */
  excludedResources?: Array<IDsResourceId> | null;

  /**
   * Resources that ignore otherwise excluding restrictions.
   */
  overrulingRestrictionResources?: Array<IDsResourceId> | null;

  /**
   * Resources that are preferred when assigning call.
   */
  preferred1Resources?: Array<IDsResourceId> | null;

  /**
   * Resources that are preferred after Preferred1Resources when assigning call.
   */
  preferred2Resources?: Array<IDsResourceId> | null;
}
