/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Coordinates of the location.
 */
export interface Coordinates {

  /**
   * Latitude of the location. Relevant for scheduling.
   */
  latitude: number;

  /**
   * Longitude of the location. Relevant for scheduling.
   */
  longitude: number;
}
