/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Determines how updating scheduled calls should be handled.<p>One of:</p>
 * <ul>
 * <li>UNSCHEDULED: Do not update scheduled calls.</li>
 * <li>WITHOUT_VIOLATIONS: Update scheduled calls only if no additional restrictions are violated compared to before the update.</li>
 * </ul>
 */
export type EnumScheduledCallUpdateModeEnum = string;
