/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Call Attributes<p>One of:</p>
 * <ul>
 * <li>SameTimeMain: Call must be scheduled at the same time as the related call</li>
 * <li>SameTimeRelated: Call must be scheduled at the same time as the main call</li>
 * <li>After: Call must be scheduled after the main call</li>
 * </ul>
 */
export type EnumCallAttributesEnum = string;
