/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Status of the call. Relevant for scheduling.
 * If used as input please use the documentation of the corresponding endpoint to get the valid values.<p>One of:</p>
 * <ul>
 * <li>RECORDED</li>
 * <li>CONFIRMED</li>
 * <li>FIXED</li>
 * <li>ON_ROUTE</li>
 * <li>ARRIVAL</li>
 * <li>COMPLETE</li>
 * <li>INCOMPLETE</li>
 * </ul>
 */
export type EnumCallStatusEnum = string;
