/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Priority of the call for the planning. Relevant for scheduling.
 * Higher priority calls may displace lower priority calls.<p>One of:</p>
 * <ul>
 * <li>LOW</li>
 * <li>NORMAL</li>
 * <li>HIGH</li>
 * <li>IMMEDIATE: Only for same day planning, call is directly inserted at the earliest possible position.</li>
 * </ul>
 */
export type EnumCallPriorityEnum = string;
