/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * In which type of shift the call can be scheduled.<p>One of:</p>
 * <ul>
 * <li>FREE: No restriction is applied.</li>
 * <li>WORKING_TIME: Call can only be scheduled in standby shifts.</li>
 * <li>STANDBY: Call can only be scheduled in working time shifts.</li>
 * </ul>
 */
export type EnumSchedulableInEnum = string;
