/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * State of an optimization.
 * Right after create an optimization it becomes the state InQueue, followed by Running when the optimization starts.
 * Canceled, Completed and Failed are final states.<p>One of:</p>
 * <ul>
 * <li>InQueue</li>
 * <li>Running</li>
 * <li>Canceling</li>
 * <li>Canceled</li>
 * <li>Completed</li>
 * <li>Failed</li>
 * <li>Undefined</li>
 * </ul>
 */
export type EnumOptimizationStateEnum = string;
