/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorDetails } from '../models/error-details';
import { ValidationErrorDetails } from '../models/validation-error-details';

/**
 * General object describing the details of an error.
 */
export interface Error {

  /**
   * List of error details.
   */
  errors?: Array<(ErrorDetails | ValidationErrorDetails)>;

  /**
   * HTTP status code.
   */
  status: string;

  /**
   * Name of the error.
   */
  title: string;

  /**
   * Id of the request for further error analysis.
   */
  traceId: string;

  /**
   * URI of the error code definition.
   */
  type: string;

  [key: string]: Array<(ErrorDetails | ValidationErrorDetails)> | any | string | undefined;
}
