/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Date } from '../models/date';
import { Time } from '../models/time';

/**
 * Restrictions regarding when the call may be planned. It consists of a time window as well as a date window.
 * In case of a time restriction that is supposed to represent an overnight time window, StartTime must be after EndTime.
 *             
 * **Use case**: Creating a call that is schedulable overnight.
 *             
 * **Use case example**: Setting StartDate and EndDate to 2024-01-01, StartTime to 20:00 and EndTime to 03:00 will result in
 * the call being schedulable at the following times:
 * - 2024-01-01T00:00:00 - 2024-01-01T03:00:00
 * - 2024-01-01T20:00:00 - 2024-01-01T23:59:59
 */
export interface IncomingTimeRestrictions {

  /**
   * Duration of the call in minutes.
   */
  duration: number;

  /**
   * Latest date to fulfill the call.
   */
  endDate: Date;

  /**
   * Latest time of the fulfillment to the minute in 24h format.
   * (Related to the time zone of the call)
   */
  endTime?: Time | null;

  /**
   * Earliest date to fulfill the call.
   */
  startDate: Date;

  /**
   * Earliest time of the fulfillment to the minute in 24h format.
   * (Related to the time zone of the call)
   */
  startTime?: Time | null;
}
