/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnumSkillProficiencyLevelEnum } from '../models/enum-skill-proficiency-level-enum';
import { IDsSkillId } from '../models/i-ds-skill-id';
export interface IncomingSkillProficiency {
  id: IDsSkillId;

  /**
   * Proficiency level for the skill
   * Penalty costs if the required skill is not available.<p>One of:</p>
   * <ul>
   * <li>LOW</li>
   * <li>MEDIUM</li>
   * <li>HIGH</li>
   * </ul>
   */
  proficiencyLevel?: EnumSkillProficiencyLevelEnum;
}
