/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OutgoingOptimizationForwardPlanning {

  /**
   * Maximum runtime of one optimization run.
   * If not set the local iteration count is used.
   */
  computingTimeInSeconds?: number | null;

  /**
   * Degree of utilization of a resource's route in percent.
   * The utilization ratio affects the working time
   * and the load capacity of a route.
   * In both cases, the original value is limited to the percentage share of
   * the utilization ratio.
   */
  utilizationRatio: number;
}
