/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OutgoingErrorDetails {

  /**
   * <p>One of:</p><ul><li>ErrorDetails</li>
   * <li>ValidationErrorDetails</li></ul>
   */
  errorDetailsType: string;
  message?: string;
}
