/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BidirectionalCoordinates } from '../models/bidirectional-coordinates';
import { IDsResourceId } from '../models/i-ds-resource-id';
import { OutgoingResourceConditions } from '../models/outgoing-resource-conditions';

/**
 * Resource
 */
export interface OutgoingResource {

  /**
   * Coordinates of the location.
   */
  coordinates: BidirectionalCoordinates;
  id: IDsResourceId;
  resourceConditions?: OutgoingResourceConditions | null;
}
