/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Date } from '../models/date';
import { Time } from '../models/time';

/**
 * Restrictions regarding when the call may be planned.
 */
export interface OutgoingTimeRestrictions {

  /**
   * Duration of the call in minutes.
   */
  duration: number;

  /**
   * Latest date to fulfill the call.
   */
  endDate: Date;

  /**
   * Latest time of the fulfillment to the minute in 24h format.
   * (Related to the time zone of the call)
   */
  endTime: Time;

  /**
   * Earliest date to fulfill the call.
   */
  startDate: Date;

  /**
   * Earliest time of the fulfillment to the minute in 24h format.
   * (Related to the time zone of the call)
   */
  startTime: Time;
}
