/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpertiseId } from '../models/expertise-id';
import { RegionId } from '../models/region-id';
import { SkillProficiency } from '../models/skill-proficiency';
import { TeamId } from '../models/team-id';
export interface ResourceConditions {

  /**
   * External identifier for the expertise id.
   */
  expertiseId?: ExpertiseId | null;

  /**
   * External identifier for the region id.
   */
  regionId?: RegionId | null;
  skills?: Array<SkillProficiency> | null;

  /**
   * External identifier for the team id.
   */
  teamId?: TeamId | null;
}
