/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Coordinates } from '../models/coordinates';
import { ResourceConditions } from '../models/resource-conditions';
import { ResourceId } from '../models/resource-id';

/**
 * Resource
 */
export interface Resource {

  /**
   * Coordinates of the location.
   */
  coordinates: Coordinates;

  /**
   * External identifier for the resource id.
   */
  id: ResourceId | null;
  resourceConditions?: ResourceConditions | null;
}
