/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SkillId } from '../models/skill-id';
import { SkillProficiencyLevelEnum } from '../models/skill-proficiency-level-enum';
export interface SkillProficiency {

  /**
   * External identifier for the skill id.
   */
  id: SkillId | null;

  /**
   * Proficiency level for the skill
   * Penalty costs if the required skill is not available.<p>One of:</p>
   * <ul>
   * <li>LOW</li>
   * <li>MEDIUM</li>
   * <li>HIGH</li>
   * </ul>
   */
  proficiencyLevel?: SkillProficiencyLevelEnum;
}
