/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorDetails } from '../models/error-details';
export type ValidationErrorDetails = ErrorDetails & {
'field'?: string;
};
