/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IDsOptimizationId } from '../../models/i-ds-optimization-id';
import { OutgoingOptimizationOptimizationDefinition } from '../../models/outgoing-optimization-optimization-definition';

export interface OptimizationGetOptimization$Params {

/**
 * Parameter within the path for the id of an optimization.
 */
  optimizationId: IDsOptimizationId;
}

export function optimizationGetOptimization(http: HttpClient, rootUrl: string, params: OptimizationGetOptimization$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingOptimizationOptimizationDefinition>> {
  const rb = new RequestBuilder(rootUrl, optimizationGetOptimization.PATH, 'get');
  if (params) {
    rb.path('optimizationId', params.optimizationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OutgoingOptimizationOptimizationDefinition>;
    })
  );
}

optimizationGetOptimization.PATH = '/v1/optimizations/{optimizationId}';
