/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IDsCallId } from '../../models/i-ds-call-id';
import { OutgoingCall } from '../../models/outgoing-call';

export interface CallGetCall$Params {

/**
 * Parameter within the path for the id of the call.
 */
  callId: IDsCallId;
}

export function callGetCall(http: HttpClient, rootUrl: string, params: CallGetCall$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingCall>> {
  const rb = new RequestBuilder(rootUrl, callGetCall.PATH, 'get');
  if (params) {
    rb.path('callId', params.callId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OutgoingCall>;
    })
  );
}

callGetCall.PATH = '/v1/calls/{callId}';
