/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IDsCallId } from '../../models/i-ds-call-id';
import { OutgoingCall } from '../../models/outgoing-call';

export interface CallGetCalls$Params {

/**
 * The number of the page to query.
 */
  page?: number;

/**
 * The number of elements per page.
 */
  pagesize?: number;

/**
 * If set, all calls (partially) matching the given id are added to the response.
 */
  id?: IDsCallId;
}

export function callGetCalls(http: HttpClient, rootUrl: string, params?: CallGetCalls$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OutgoingCall>>> {
  const rb = new RequestBuilder(rootUrl, callGetCalls.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pagesize', params.pagesize, {});
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OutgoingCall>>;
    })
  );
}

callGetCalls.PATH = '/v1/calls';
