/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnumScheduledCallUpdateModeEnum } from '../../models/enum-scheduled-call-update-mode-enum';
import { IDsCallId } from '../../models/i-ds-call-id';
import { IncomingCall } from '../../models/incoming-call';

export interface CallUpdateCall$Params {

/**
 * Parameter within the path for the id of the call to update.
 */
  callId: IDsCallId;

/**
 * <p>One of:</p>
 * <ul>
 * <li>UNSCHEDULED: Do not update scheduled calls.</li>
 * <li>WITHOUT_VIOLATIONS: Update scheduled calls only if no additional restrictions are violated compared to before the update.</li>
 * </ul>
 */
  scheduledCallUpdateMode?: EnumScheduledCallUpdateModeEnum;
  
    /**
     * The call data.
     */
    body: IncomingCall
}

export function callUpdateCall(http: HttpClient, rootUrl: string, params: CallUpdateCall$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, callUpdateCall.PATH, 'put');
  if (params) {
    rb.path('callId', params.callId, {});
    rb.query('scheduledCallUpdateMode', params.scheduledCallUpdateMode, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

callUpdateCall.PATH = '/v1/calls/{callId}';
