/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IDsCallId } from '../../models/i-ds-call-id';

export interface CallDeleteCall$Params {

/**
 * Parameter within the path for the id of the call to delete.
 */
  callId: IDsCallId;
}

export function callDeleteCall(http: HttpClient, rootUrl: string, params: CallDeleteCall$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, callDeleteCall.PATH, 'delete');
  if (params) {
    rb.path('callId', params.callId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

callDeleteCall.PATH = '/v1/calls/{callId}';
