/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { callCreateCall } from '../fn/call/call-create-call';
import { CallCreateCall$Params } from '../fn/call/call-create-call';
import { callDeleteCall } from '../fn/call/call-delete-call';
import { CallDeleteCall$Params } from '../fn/call/call-delete-call';
import { callGetCall } from '../fn/call/call-get-call';
import { CallGetCall$Params } from '../fn/call/call-get-call';
import { callGetCalls } from '../fn/call/call-get-calls';
import { CallGetCalls$Params } from '../fn/call/call-get-calls';
import { callUpdateCall } from '../fn/call/call-update-call';
import { CallUpdateCall$Params } from '../fn/call/call-update-call';
import { OutgoingCall } from '../models/outgoing-call';

@Injectable({ providedIn: 'root' })
export class CallApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `callGetCalls()` */
  static readonly CallGetCallsPath = '/v1/calls';

  /**
   * Get a list of calls that (partially) match specified ID.
   *
   * Retrieves a list of calls that (partially) match specified ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `callGetCalls()` instead.
   *
   * This method doesn't expect any request body.
   */
  callGetCalls$Response(params?: CallGetCalls$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OutgoingCall>>> {
    return callGetCalls(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of calls that (partially) match specified ID.
   *
   * Retrieves a list of calls that (partially) match specified ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `callGetCalls$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  callGetCalls(params?: CallGetCalls$Params, context?: HttpContext): Observable<Array<OutgoingCall>> {
    return this.callGetCalls$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OutgoingCall>>): Array<OutgoingCall> => r.body)
    );
  }

  /** Path part for operation `callCreateCall()` */
  static readonly CallCreateCallPath = '/v1/calls';

  /**
   * Create a new call.
   *
   * Creates a new call with the sent main data.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `callCreateCall()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  callCreateCall$Response(params: CallCreateCall$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingCall>> {
    return callCreateCall(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new call.
   *
   * Creates a new call with the sent main data.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `callCreateCall$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  callCreateCall(params: CallCreateCall$Params, context?: HttpContext): Observable<OutgoingCall> {
    return this.callCreateCall$Response(params, context).pipe(
      map((r: StrictHttpResponse<OutgoingCall>): OutgoingCall => r.body)
    );
  }

  /** Path part for operation `callGetCall()` */
  static readonly CallGetCallPath = '/v1/calls/{callId}';

  /**
   * Get the call with specified id.
   *
   * Retrieves the call with the specified id.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `callGetCall()` instead.
   *
   * This method doesn't expect any request body.
   */
  callGetCall$Response(params: CallGetCall$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingCall>> {
    return callGetCall(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the call with specified id.
   *
   * Retrieves the call with the specified id.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `callGetCall$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  callGetCall(params: CallGetCall$Params, context?: HttpContext): Observable<OutgoingCall> {
    return this.callGetCall$Response(params, context).pipe(
      map((r: StrictHttpResponse<OutgoingCall>): OutgoingCall => r.body)
    );
  }

  /** Path part for operation `callUpdateCall()` */
  static readonly CallUpdateCallPath = '/v1/calls/{callId}';

  /**
   * Update a call.
   *
   * Updates a call with the given callId.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `callUpdateCall()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  callUpdateCall$Response(params: CallUpdateCall$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return callUpdateCall(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a call.
   *
   * Updates a call with the given callId.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `callUpdateCall$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  callUpdateCall(params: CallUpdateCall$Params, context?: HttpContext): Observable<void> {
    return this.callUpdateCall$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `callDeleteCall()` */
  static readonly CallDeleteCallPath = '/v1/calls/{callId}';

  /**
   * Delete a call.
   *
   * Deletes a call with the given callId.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `callDeleteCall()` instead.
   *
   * This method doesn't expect any request body.
   */
  callDeleteCall$Response(params: CallDeleteCall$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return callDeleteCall(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a call.
   *
   * Deletes a call with the given callId.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `callDeleteCall$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  callDeleteCall(params: CallDeleteCall$Params, context?: HttpContext): Observable<void> {
    return this.callDeleteCall$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
