/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { optimizationCreateOptimization } from '../fn/optimization/optimization-create-optimization';
import { OptimizationCreateOptimization$Params } from '../fn/optimization/optimization-create-optimization';
import { optimizationDeleteOptimization } from '../fn/optimization/optimization-delete-optimization';
import { OptimizationDeleteOptimization$Params } from '../fn/optimization/optimization-delete-optimization';
import { optimizationGetOptimization } from '../fn/optimization/optimization-get-optimization';
import { OptimizationGetOptimization$Params } from '../fn/optimization/optimization-get-optimization';
import { optimizationGetOptimizationState } from '../fn/optimization/optimization-get-optimization-state';
import { OptimizationGetOptimizationState$Params } from '../fn/optimization/optimization-get-optimization-state';
import { OutgoingOptimizationOptimizationDefinition } from '../models/outgoing-optimization-optimization-definition';
import { OutgoingOptimizationStateDefinition } from '../models/outgoing-optimization-state-definition';


/**
 * An optimization seeks to determine the best route for resources, taking into account their limitations and benefits.
 */
@Injectable({ providedIn: 'root' })
export class OptimizationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `optimizationCreateOptimization()` */
  static readonly OptimizationCreateOptimizationPath = '/v1/optimizations';

  /**
   * Start a new optimization.
   *
   * Start a new optimization asynchronously and return the id. By default, only scheduled calls are optimized. To optimize unscheduled calls
   * as well, a RecordedCallsFilter or EscalatedCallsFilter needs to be provided.
   *             
   * **Use case 1**: Starting an optimization to improve the efficiency all resources and calls according to the global filter.
   * **Use case 1 example**: An optimization without resources and global filters will apply the global filter to all calls and resources.
   *             
   * **Use case 2**: Starting an optimization to improve the efficiency of the given resources.
   * **Use case 2 example**: An optimization with resources and global filters will only apply the global filter to the unplanned calls.
   *             
   * **Use case 3**: Starting an optimization for scheduled calls only, to optimize the routes without removing or adding new calls to them.
   * **Use case 3 example**: An optimization without recorded calls filter or escalated calls filter.
   *             
   * **Use case 4**: Starting an optimization after creating some calls to automatically schedule them at their ideal times in routes, as well as optimzing
   * already scheduled calls.
   * **Use case 4 example**: An optimizazion with a recorded calls filter that matches the unscheduled calls to be scheduled.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `optimizationCreateOptimization()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  optimizationCreateOptimization$Response(params: OptimizationCreateOptimization$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingOptimizationOptimizationDefinition>> {
    return optimizationCreateOptimization(this.http, this.rootUrl, params, context);
  }

  /**
   * Start a new optimization.
   *
   * Start a new optimization asynchronously and return the id. By default, only scheduled calls are optimized. To optimize unscheduled calls
   * as well, a RecordedCallsFilter or EscalatedCallsFilter needs to be provided.
   *             
   * **Use case 1**: Starting an optimization to improve the efficiency all resources and calls according to the global filter.
   * **Use case 1 example**: An optimization without resources and global filters will apply the global filter to all calls and resources.
   *             
   * **Use case 2**: Starting an optimization to improve the efficiency of the given resources.
   * **Use case 2 example**: An optimization with resources and global filters will only apply the global filter to the unplanned calls.
   *             
   * **Use case 3**: Starting an optimization for scheduled calls only, to optimize the routes without removing or adding new calls to them.
   * **Use case 3 example**: An optimization without recorded calls filter or escalated calls filter.
   *             
   * **Use case 4**: Starting an optimization after creating some calls to automatically schedule them at their ideal times in routes, as well as optimzing
   * already scheduled calls.
   * **Use case 4 example**: An optimizazion with a recorded calls filter that matches the unscheduled calls to be scheduled.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `optimizationCreateOptimization$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  optimizationCreateOptimization(params: OptimizationCreateOptimization$Params, context?: HttpContext): Observable<OutgoingOptimizationOptimizationDefinition> {
    return this.optimizationCreateOptimization$Response(params, context).pipe(
      map((r: StrictHttpResponse<OutgoingOptimizationOptimizationDefinition>): OutgoingOptimizationOptimizationDefinition => r.body)
    );
  }

  /** Path part for operation `optimizationGetOptimization()` */
  static readonly OptimizationGetOptimizationPath = '/v1/optimizations/{optimizationId}';

  /**
   * Get information of a started optimization with specified id. For retrieving information about the current state
   * of the optimization use the endpoint "/optimizations/{optimizationId}/state".
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `optimizationGetOptimization()` instead.
   *
   * This method doesn't expect any request body.
   */
  optimizationGetOptimization$Response(params: OptimizationGetOptimization$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingOptimizationOptimizationDefinition>> {
    return optimizationGetOptimization(this.http, this.rootUrl, params, context);
  }

  /**
   * Get information of a started optimization with specified id. For retrieving information about the current state
   * of the optimization use the endpoint "/optimizations/{optimizationId}/state".
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `optimizationGetOptimization$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  optimizationGetOptimization(params: OptimizationGetOptimization$Params, context?: HttpContext): Observable<OutgoingOptimizationOptimizationDefinition> {
    return this.optimizationGetOptimization$Response(params, context).pipe(
      map((r: StrictHttpResponse<OutgoingOptimizationOptimizationDefinition>): OutgoingOptimizationOptimizationDefinition => r.body)
    );
  }

  /** Path part for operation `optimizationDeleteOptimization()` */
  static readonly OptimizationDeleteOptimizationPath = '/v1/optimizations/{optimizationId}';

  /**
   * Stop an optimization.
   *
   * Stops a scheduled or running optimization.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `optimizationDeleteOptimization()` instead.
   *
   * This method doesn't expect any request body.
   */
  optimizationDeleteOptimization$Response(params: OptimizationDeleteOptimization$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return optimizationDeleteOptimization(this.http, this.rootUrl, params, context);
  }

  /**
   * Stop an optimization.
   *
   * Stops a scheduled or running optimization.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `optimizationDeleteOptimization$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  optimizationDeleteOptimization(params: OptimizationDeleteOptimization$Params, context?: HttpContext): Observable<void> {
    return this.optimizationDeleteOptimization$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `optimizationGetOptimizationState()` */
  static readonly OptimizationGetOptimizationStatePath = '/v1/optimizations/{optimizationId}/state';

  /**
   * Get the state of a running optimization with specified id.
   *
   * Retrieves the optimization state of a running optimization with the specified id. After completion of an optimization,
   * it will be available with state "Completed" or "Cancelled" for two minutes before being removed from the system. When requesting a removed
   * optimization state, an HTTP response code 404 will be sent.
   *             
   * **Use case**: Fetching the state of a started optimization to see its progress with its Id. The optimization has been completed a long time ago (e.g. 10 minutes).
   * **Use case example**: Because the optimization has been completed a while ago, the Id is not found in the system anymore and HTTP status code 404 is returned.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `optimizationGetOptimizationState()` instead.
   *
   * This method doesn't expect any request body.
   */
  optimizationGetOptimizationState$Response(params: OptimizationGetOptimizationState$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingOptimizationStateDefinition>> {
    return optimizationGetOptimizationState(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the state of a running optimization with specified id.
   *
   * Retrieves the optimization state of a running optimization with the specified id. After completion of an optimization,
   * it will be available with state "Completed" or "Cancelled" for two minutes before being removed from the system. When requesting a removed
   * optimization state, an HTTP response code 404 will be sent.
   *             
   * **Use case**: Fetching the state of a started optimization to see its progress with its Id. The optimization has been completed a long time ago (e.g. 10 minutes).
   * **Use case example**: Because the optimization has been completed a while ago, the Id is not found in the system anymore and HTTP status code 404 is returned.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `optimizationGetOptimizationState$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  optimizationGetOptimizationState(params: OptimizationGetOptimizationState$Params, context?: HttpContext): Observable<OutgoingOptimizationStateDefinition> {
    return this.optimizationGetOptimizationState$Response(params, context).pipe(
      map((r: StrictHttpResponse<OutgoingOptimizationStateDefinition>): OutgoingOptimizationStateDefinition => r.body)
    );
  }

}
