/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { OutgoingResource } from '../models/outgoing-resource';
import { resourceCreateResource } from '../fn/resource/resource-create-resource';
import { ResourceCreateResource$Params } from '../fn/resource/resource-create-resource';
import { resourceDeleteResource } from '../fn/resource/resource-delete-resource';
import { ResourceDeleteResource$Params } from '../fn/resource/resource-delete-resource';
import { resourceGetResource } from '../fn/resource/resource-get-resource';
import { ResourceGetResource$Params } from '../fn/resource/resource-get-resource';
import { resourceGetResources } from '../fn/resource/resource-get-resources';
import { ResourceGetResources$Params } from '../fn/resource/resource-get-resources';
import { resourceUpdateResource } from '../fn/resource/resource-update-resource';
import { ResourceUpdateResource$Params } from '../fn/resource/resource-update-resource';

@Injectable({ providedIn: 'root' })
export class ResourceApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `resourceGetResources()` */
  static readonly ResourceGetResourcesPath = '/v1/resources';

  /**
   * Get a list of resources.
   *
   * Retrieves a list of resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resourceGetResources()` instead.
   *
   * This method doesn't expect any request body.
   */
  resourceGetResources$Response(params?: ResourceGetResources$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OutgoingResource>>> {
    return resourceGetResources(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of resources.
   *
   * Retrieves a list of resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resourceGetResources$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resourceGetResources(params?: ResourceGetResources$Params, context?: HttpContext): Observable<Array<OutgoingResource>> {
    return this.resourceGetResources$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OutgoingResource>>): Array<OutgoingResource> => r.body)
    );
  }

  /** Path part for operation `resourceCreateResource()` */
  static readonly ResourceCreateResourcePath = '/v1/resources';

  /**
   * Create a new resource.
   *
   * Creates a new resource with the sent main data.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resourceCreateResource()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resourceCreateResource$Response(params: ResourceCreateResource$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingResource>> {
    return resourceCreateResource(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new resource.
   *
   * Creates a new resource with the sent main data.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resourceCreateResource$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resourceCreateResource(params: ResourceCreateResource$Params, context?: HttpContext): Observable<OutgoingResource> {
    return this.resourceCreateResource$Response(params, context).pipe(
      map((r: StrictHttpResponse<OutgoingResource>): OutgoingResource => r.body)
    );
  }

  /** Path part for operation `resourceGetResource()` */
  static readonly ResourceGetResourcePath = '/v1/resources/{resourceId}';

  /**
   * Get the resource with the specified id.
   *
   * Retrieves the resource with the specified id with belonging capabilities and coordinates.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resourceGetResource()` instead.
   *
   * This method doesn't expect any request body.
   */
  resourceGetResource$Response(params: ResourceGetResource$Params, context?: HttpContext): Observable<StrictHttpResponse<OutgoingResource>> {
    return resourceGetResource(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the resource with the specified id.
   *
   * Retrieves the resource with the specified id with belonging capabilities and coordinates.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resourceGetResource$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resourceGetResource(params: ResourceGetResource$Params, context?: HttpContext): Observable<OutgoingResource> {
    return this.resourceGetResource$Response(params, context).pipe(
      map((r: StrictHttpResponse<OutgoingResource>): OutgoingResource => r.body)
    );
  }

  /** Path part for operation `resourceUpdateResource()` */
  static readonly ResourceUpdateResourcePath = '/v1/resources/{resourceId}';

  /**
   * Update an resource.
   *
   * Updates the resource with the specified id.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resourceUpdateResource()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resourceUpdateResource$Response(params: ResourceUpdateResource$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return resourceUpdateResource(this.http, this.rootUrl, params, context);
  }

  /**
   * Update an resource.
   *
   * Updates the resource with the specified id.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resourceUpdateResource$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resourceUpdateResource(params: ResourceUpdateResource$Params, context?: HttpContext): Observable<void> {
    return this.resourceUpdateResource$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `resourceDeleteResource()` */
  static readonly ResourceDeleteResourcePath = '/v1/resources/{resourceId}';

  /**
   * Delete the resource with the specified id.
   *
   * Deletes the resource with the specified id.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resourceDeleteResource()` instead.
   *
   * This method doesn't expect any request body.
   */
  resourceDeleteResource$Response(params: ResourceDeleteResource$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return resourceDeleteResource(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete the resource with the specified id.
   *
   * Deletes the resource with the specified id.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resourceDeleteResource$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resourceDeleteResource(params: ResourceDeleteResource$Params, context?: HttpContext): Observable<void> {
    return this.resourceDeleteResource$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
