/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IDsExpertiseId } from '../models/i-ds-expertise-id';
import { IDsRegionId } from '../models/i-ds-region-id';
import { IDsTeamId } from '../models/i-ds-team-id';
export interface BidirectionalGlobalFilters {

  /**
   * Only items with expertise matching one of the given expertises are considered. If omitted, items are not filtered by expertises.
   */
  expertises?: Array<IDsExpertiseId> | null;

  /**
   * * true: Consider items without assigned expertise.
   * * false: Consider items with assigned expertise.
   * * null:
   *   * if *globalFilters.expertises* is not set, there is no filtering by this attribute (not the same as true, because then only unassigned would be considered).
   *   * if *globalFilters.expertises* is set, items with unassigned attribute are ignored (same effect as false).
   */
  includeUnassignedExpertises?: boolean | null;

  /**
   * * true: Consider items without assigned regions.
   * * false: Consider items with assigned regions.
   * * null:
   *   * if *globalFilters.regions* is not set, there is no filtering by this attribute (not the same as true, because then only unassigned would be considered).
   *   * if *globalFilters.regions* is set, items with unassigned attribute are ignored (same effect as false).
   */
  includeUnassignedRegions?: boolean | null;

  /**
   * * true: Consider items without assigned teams.
   * * false: Consider items with assigned teams.
   * * null:
   *   * if *globalFilters.teams* is not set, there is no filtering by this attribute (not the same as true, because then only unassigned would be considered).
   *   * if *globalFilters.teams* is set, items with unassigned attribute are ignored (same effect as false).
   */
  includeUnassignedTeams?: boolean | null;

  /**
   * Only items with region matching one of the given regions are considered. If omitted, items are not filtered by region.
   */
  regions?: Array<IDsRegionId> | null;

  /**
   * Only items with team matching one of the given teams are considered. If omitted, items are not filtered by teams.
   */
  teams?: Array<IDsTeamId> | null;
}
