/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Reserve type of the call.<p>One of:</p>
 * <ul>
 * <li>NONE: No reservation.</li>
 * <li>NOT_FIXABLE: Call cannot be fixed.</li>
 * <li>NO_AUTOMATIC_SCHEDULING: Call is only scheduled by manual operations like confirmation or moving, not by general optimizations.</li>
 * <li>DEFERRED: Same as NO_AUTOMATIC_SCHEDULING but the DEFERRED reservation is reset automatically every night.</li>
 * </ul>
 */
export type EnumReserveTypeEnum = string;
