/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Proficiency level for a skill.<p>One of:</p>
 * <ul>
 * <li>LOW</li>
 * <li>MEDIUM</li>
 * <li>HIGH</li>
 * </ul>
 */
export type EnumSkillProficiencyLevelEnum = string;
