/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IDsExpertiseId } from '../models/i-ds-expertise-id';
import { IDsRegionId } from '../models/i-ds-region-id';
import { IDsTeamId } from '../models/i-ds-team-id';
import { IncomingSkillProficiency } from '../models/incoming-skill-proficiency';
export interface IncomingResourceConditions {
  expertiseId?: IDsExpertiseId | null;
  regionId?: IDsRegionId | null;
  skills?: Array<IncomingSkillProficiency> | null;
  teamId?: IDsTeamId | null;
}
