/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BidirectionalEscalatedCallsFilter } from '../models/bidirectional-escalated-calls-filter';
import { BidirectionalGlobalFilters } from '../models/bidirectional-global-filters';
import { BidirectionalRecordedCallsFilter } from '../models/bidirectional-recorded-calls-filter';
import { Date } from '../models/date';
import { EnumCallPriorityEnum } from '../models/enum-call-priority-enum';
import { IDsCallTypeId } from '../models/i-ds-call-type-id';
import { IDsOptimizationId } from '../models/i-ds-optimization-id';
import { IDsResourceId } from '../models/i-ds-resource-id';
import { IncomingOptimizationForwardPlanning } from '../models/incoming-optimization-forward-planning';

/**
 * Information for an optimization.
 */
export interface IncomingOptimizationOptimizationDefinition {

  /**
   * If set, all calls fulfilling the call type id filter constrains are considered.
   */
  callTypeIds?: Array<IDsCallTypeId> | null;

  /**
   * End date of the date range.
   * The maximum daterange is 365 days.
   */
  endDate?: Date;

  /**
   * If set, all escalated calls fulfilling all given date constraints are considered.
   */
  escalatedCallsFilter?: BidirectionalEscalatedCallsFilter | null;

  /**
   * Settings for forward planning.
   */
  forwardPlanning?: IncomingOptimizationForwardPlanning | null;

  /**
   * If set, all calls fulfilling the global filter constrains are considered.
   */
  globalFilters?: BidirectionalGlobalFilters | null;

  /**
   * Id of the optimization.
   */
  id?: IDsOptimizationId | null;

  /**
   * If set, all calls fulfilling the priority filter constrains are considered.
   */
  priorities?: Array<EnumCallPriorityEnum> | null;

  /**
   * If set, all unscheduled recorded calls fulfilling all given date constraints are considered.
   */
  recordedCallsFilter?: BidirectionalRecordedCallsFilter | null;

  /**
   * Reduces the optimization to these resources, when given.
   */
  resourceIds?: Array<IDsResourceId> | null;

  /**
   * Start date of the date range.
   */
  startDate?: Date;
}
