/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BidirectionalCoordinates } from '../models/bidirectional-coordinates';
import { IDsResourceId } from '../models/i-ds-resource-id';
import { IncomingResourceConditions } from '../models/incoming-resource-conditions';

/**
 * Resource
 */
export interface IncomingResource {

  /**
   * Coordinates of the location.
   */
  coordinates: BidirectionalCoordinates;
  id: IDsResourceId;
  resourceConditions?: IncomingResourceConditions | null;
}
