/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnumSchedulableInEnum } from '../models/enum-schedulable-in-enum';
import { IDsExpertiseId } from '../models/i-ds-expertise-id';
import { IDsGeneralRouteId } from '../models/i-ds-general-route-id';
import { IDsRegionId } from '../models/i-ds-region-id';
import { IDsTeamId } from '../models/i-ds-team-id';
import { IncomingSkillProficiency } from '../models/incoming-skill-proficiency';
export interface IncomingRouteConditions {

  /**
   * Expertise the call is assigned to.
   */
  expertiseId?: IDsExpertiseId | null;

  /**
   * General route that the call will be scheduled to.
   */
  generalRouteId?: IDsGeneralRouteId | null;

  /**
   * Region the call is assigned to.
   */
  regionId?: IDsRegionId | null;

  /**
   * In which type of shift the call can be scheduled.<p>One of:</p>
   * <ul>
   * <li>FREE: No restriction is applied.</li>
   * <li>WORKING_TIME: Call can only be scheduled in standby shifts.</li>
   * <li>STANDBY: Call can only be scheduled in working time shifts.</li>
   * </ul>
   */
  schedulableIn?: EnumSchedulableInEnum;

  /**
   * Required skills to handle the call.
   */
  skills?: Array<IncomingSkillProficiency> | null;

  /**
   * Team the call is assigned to.
   */
  teamId?: IDsTeamId | null;

  /**
   * Quantity requirement for transport unit 1.
   */
  transportUnit1?: number;

  /**
   * Quantity requirement for transport unit 2.
   */
  transportUnit2?: number;
}
