/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BidirectionalCoordinates } from '../models/bidirectional-coordinates';
import { BidirectionalResourceRestrictions } from '../models/bidirectional-resource-restrictions';
import { Date } from '../models/date';
import { EnumCallAttributesEnum } from '../models/enum-call-attributes-enum';
import { EnumCallPriorityEnum } from '../models/enum-call-priority-enum';
import { EnumCallStatusEnum } from '../models/enum-call-status-enum';
import { EnumReserveTypeEnum } from '../models/enum-reserve-type-enum';
import { IDsCallId } from '../models/i-ds-call-id';
import { IDsCallTypeId } from '../models/i-ds-call-type-id';
import { IncomingRouteConditions } from '../models/incoming-route-conditions';
import { IncomingTimeRestrictions } from '../models/incoming-time-restrictions';
export interface IncomingCall {

  /**
   * Attributes indicating special call properties.
   */
  attributes?: Array<EnumCallAttributesEnum> | null;
  callTypeId?: IDsCallTypeId | null;

  /**
   * Coordinates of the location.
   */
  coordinates: BidirectionalCoordinates;

  /**
   * Additional value of call to prioritize it in optimization.
   */
  extraValue?: number | null;

  /**
   * External identifier for the call.
   */
  id: IDsCallId;

  /**
   * Priority of the call for the planning. Relevant for scheduling.
   * Higher priority calls may displace lower priority calls.<p>One of:</p>
   * <ul>
   * <li>LOW</li>
   * <li>NORMAL</li>
   * <li>HIGH</li>
   * <li>IMMEDIATE: Only for same day planning, call is directly inserted at the earliest possible position.</li>
   * </ul>
   */
  priority?: EnumCallPriorityEnum | null;

  /**
   * Attributes indicating call reserve type.<p>One of:</p>
   * <ul>
   * <li>NONE: No reservation.</li>
   * <li>NOT_FIXABLE: Call cannot be fixed.</li>
   * <li>NO_AUTOMATIC_SCHEDULING: Call is only scheduled by manual operations like confirmation or moving, not by general optimizations.</li>
   * <li>DEFERRED: Same as NO_AUTOMATIC_SCHEDULING but the DEFERRED reservation is reset automatically every night.</li>
   * </ul>
   */
  reserveType?: EnumReserveTypeEnum | null;

  /**
   * Restrictions regarding where the call may be planned.
   */
  resourceRestrictions?: BidirectionalResourceRestrictions | null;
  routeConditions?: IncomingRouteConditions | null;
  routeDate?: Date | null;

  /**
   * Status of the call. Relevant for scheduling.<p>One of:</p>
   * <ul>
   * <li>RECORDED</li>
   * <li>CONFIRMED</li>
   * <li>FIXED</li>
   * <li>ON_ROUTE</li>
   * <li>ARRIVAL</li>
   * <li>COMPLETE</li>
   * <li>INCOMPLETE</li>
   * </ul>
   */
  status?: EnumCallStatusEnum | null;

  /**
   * Restrictions regarding when the call may be planned. It consists of a time window as well as a date window.
   * In case of a time restriction that is supposed to represent an overnight time window, StartTime must be after EndTime.
   *             
   * **Use case**: Creating a call that is schedulable overnight.
   *             
   * **Use case example**: Setting StartDate and EndDate to 2024-01-01, StartTime to 20:00 and EndTime to 03:00 will result in
   * the call being schedulable at the following times:
   * - 2024-01-01T00:00:00 - 2024-01-01T03:00:00
   * - 2024-01-01T20:00:00 - 2024-01-01T23:59:59
   */
  timeRestrictions: IncomingTimeRestrictions;
}
