/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OutgoingErrorDetails } from '../models/outgoing-error-details';
export type OutgoingValidationErrorDetails = OutgoingErrorDetails & {
'field'?: string;
};
