/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IDsExpertiseId } from '../models/i-ds-expertise-id';
import { IDsRegionId } from '../models/i-ds-region-id';
import { IDsTeamId } from '../models/i-ds-team-id';
import { OutgoingSkillProficiency } from '../models/outgoing-skill-proficiency';
export interface OutgoingResourceConditions {
  expertiseId?: IDsExpertiseId | null;
  regionId?: IDsRegionId | null;
  skills?: Array<OutgoingSkillProficiency> | null;
  teamId?: IDsTeamId | null;
}
